import os
import tempfile
from pathlib import Path

import pytest

from argcomplete_fish.cli import main


def test_cli_output_stdout(mocker, capsys):
    mocker.patch("sys.argv", ["argcomplete-fish", "tests.test_inspector:parser"])
    main()
    captured = capsys.readouterr()
    assert "complete -c my_global" in captured.out
    assert "# Generated by argcomplete-fish" in captured.out


def test_cli_output_file(mocker):
    with tempfile.TemporaryDirectory() as tmpdir:
        out_path = Path(tmpdir) / "out.fish"
        mocker.patch(
            "sys.argv",
            ["argcomplete-fish", "tests.test_inspector:parser", "-o", str(out_path)],
        )
        main()

        with out_path.open("r") as f:
            content = f.read()
            assert "complete -c my_global" in content


def test_cli_append_file(mocker):
    with tempfile.TemporaryDirectory() as tmpdir:
        out_path = Path(tmpdir) / "out.fish"
        with out_path.open("w") as f:
            f.write("# existing file\n")

        mocker.patch(
            "sys.argv",
            ["argcomplete-fish", "tests.test_inspector:parser", "-a", str(out_path)],
        )
        main()

        with out_path.open("r") as f:
            content = f.read()
            assert "# existing file" in content
            assert "complete -c my_global" in content


def test_cli_name_override(mocker, capsys):
    mocker.patch(
        "sys.argv",
        [
            "argcomplete-fish",
            "tests.test_inspector:parser",
            "--name",
            "my_custom_cmd",
        ],
    )
    main()
    captured = capsys.readouterr()
    assert "complete -c my_custom_cmd" in captured.out
    assert "my_global" not in captured.out


def test_cli_invalid_target(mocker, capsys):
    mocker.patch("sys.argv", ["argcomplete-fish", "invalid_target"])
    with pytest.raises(SystemExit) as e:
        main()
    assert e.value.code == 1
    captured = capsys.readouterr()
    assert "Error loading parser" in captured.err


def test_cli_auto_save_with_xdg(mocker):
    with tempfile.TemporaryDirectory() as tmpdir:
        mocker.patch.dict(os.environ, {"XDG_CONFIG_HOME": tmpdir})
        mocker.patch(
            "sys.argv",
            ["argcomplete-fish", "tests.test_inspector:parser", "--auto-save"],
        )
        main()

        expected_path = Path(tmpdir) / "fish" / "completions" / "my_global.fish"
        assert expected_path.exists()
        with expected_path.open("r") as f:
            content = f.read()
            assert "complete -c my_global" in content


def test_cli_auto_save_fallback(mocker):
    with tempfile.TemporaryDirectory() as tmpdir:
        # delete XDG_CONFIG_HOME if present
        mocker.patch.dict(os.environ, {}, clear=True)
        mocker.patch("pathlib.Path.home", return_value=Path(tmpdir))
        mocker.patch(
            "sys.argv",
            ["argcomplete-fish", "tests.test_inspector:parser", "--auto-save"],
        )
        main()

        expected_path = (
            Path(tmpdir) / ".config" / "fish" / "completions" / "my_global.fish"
        )
        assert expected_path.exists()
        with expected_path.open("r") as f:
            content = f.read()
            assert "complete -c my_global" in content


@pytest.mark.parametrize(
    "invalid_prog_name",
    [
        "argcomplete-fish",
        "cli.py",
        "python -m src.argcomplete_fish.cli",
        "",
        "   ",
    ],
)
def test_cli_improper_inference_fallback(mocker, capsys, invalid_prog_name):
    mock_parser = mocker.MagicMock()
    mock_parser.prog = invalid_prog_name
    mocker.patch("argcomplete_fish.cli.load_parser", return_value=mock_parser)
    mocker.patch("sys.argv", ["argcomplete-fish", "tests.test_inspector:parser"])

    main()

    captured = capsys.readouterr()
    assert "Warning: Could not infer a meaningful command name" in captured.err
    assert "Fish completions for unknown_command" in captured.out


@pytest.mark.parametrize(
    "invalid_prog_name",
    [
        "argcomplete-fish",
        "cli.py",
        "python -m src.argcomplete_fish.cli",
        "",
        "   ",
    ],
)
def test_cli_improper_inference_with_override(mocker, capsys, invalid_prog_name):
    mock_parser = mocker.MagicMock()
    mock_parser.prog = invalid_prog_name
    mocker.patch("argcomplete_fish.cli.load_parser", return_value=mock_parser)
    mocker.patch(
        "sys.argv",
        [
            "argcomplete-fish",
            "tests.test_inspector:parser",
            "--name",
            "my_explicit_name",
        ],
    )

    main()

    captured = capsys.readouterr()
    assert "Warning: Could not infer a meaningful command name" not in captured.err
    assert "Fish completions for my_explicit_name" in captured.out
