import os
import tempfile

import pytest

from argcomplete_fish.cli import main


def test_cli_output_stdout(mocker, capsys):
    mocker.patch("sys.argv", ["argcomplete-fish", "tests.test_inspector:parser"])
    main()
    captured = capsys.readouterr()
    assert "complete -c my_global" in captured.out
    assert "# Generated by argcomplete-fish" in captured.out


def test_cli_output_file(mocker):
    with tempfile.TemporaryDirectory() as tmpdir:
        out_path = os.path.join(tmpdir, "out.fish")
        mocker.patch(
            "sys.argv",
            ["argcomplete-fish", "tests.test_inspector:parser", "-o", out_path],
        )
        main()

        with open(out_path, "r") as f:
            content = f.read()
            assert "complete -c my_global" in content


def test_cli_append_file(mocker):
    with tempfile.TemporaryDirectory() as tmpdir:
        out_path = os.path.join(tmpdir, "out.fish")
        with open(out_path, "w") as f:
            f.write("# existing file\n")

        mocker.patch(
            "sys.argv",
            ["argcomplete-fish", "tests.test_inspector:parser", "-a", out_path],
        )
        main()

        with open(out_path, "r") as f:
            content = f.read()
            assert "# existing file" in content
            assert "complete -c my_global" in content


def test_cli_name_override(mocker, capsys):
    mocker.patch(
        "sys.argv",
        [
            "argcomplete-fish",
            "tests.test_inspector:parser",
            "--name",
            "my_custom_cmd",
        ],
    )
    main()
    captured = capsys.readouterr()
    assert "complete -c my_custom_cmd" in captured.out
    assert "my_global" not in captured.out


def test_cli_invalid_target(mocker, capsys):
    mocker.patch("sys.argv", ["argcomplete-fish", "invalid_target"])
    with pytest.raises(SystemExit) as e:
        main()
    assert e.value.code == 1
    captured = capsys.readouterr()
    assert "Error loading parser" in captured.err
